"use server";
import { revalidatePath } from "next/cache";
import { prisma } from "../../../src/lib/prisma";
import { requireCurrentWorkspace } from "../../../src/auth/current-workspace";
import { payrollNet } from "../../../src/application/workforce/workforce-center-service";
const text=(fd:FormData,key:string)=>String(fd.get(key)??"").trim();
const money=(fd:FormData,key:string)=>{const raw=text(fd,key).replace(/[,\s]/g,"");if(!/^\d+$/.test(raw))throw new Error(`INVALID_${key.toUpperCase()}`);return BigInt(raw)};
export async function createEmployeeAction(fd:FormData){const c=await requireCurrentWorkspace();if(c.role==="VIEWER")throw new Error("PAYROLL_WRITE_FORBIDDEN");const employeeCode=text(fd,"employeeCode"),name=text(fd,"name");if(!employeeCode||!name)throw new Error("EMPLOYEE_REQUIRED_FIELDS");await prisma.employee.create({data:{workspaceId:c.workspace.id,employeeCode,name,nationalId:text(fd,"nationalId")||null,mobile:text(fd,"mobile")||null,baseSalary:money(fd,"baseSalary")}});revalidatePath("/app/payroll")}
export async function createPayrollRunAction(fd:FormData){const c=await requireCurrentWorkspace();if(c.role==="VIEWER")throw new Error("PAYROLL_WRITE_FORBIDDEN");const employeeId=text(fd,"employeeId");const employee=await prisma.employee.findFirst({where:{id:employeeId,workspaceId:c.workspace.id,active:true}});if(!employee)throw new Error("EMPLOYEE_NOT_FOUND");const grossPay=money(fd,"grossPay"),deductions=money(fd,"deductions"),netPay=payrollNet(grossPay,deductions);const periodStart=new Date(text(fd,"periodStart")),periodEnd=new Date(text(fd,"periodEnd"));if(!Number.isFinite(periodStart.getTime())||!Number.isFinite(periodEnd.getTime())||periodEnd<periodStart)throw new Error("PAYROLL_PERIOD_INVALID");await prisma.payrollRun.create({data:{workspaceId:c.workspace.id,title:text(fd,"title")||"دوره حقوق",periodStart,periodEnd,lines:{create:{employeeId,grossPay,deductions,netPay,note:text(fd,"note")||null}}}});revalidatePath("/app/payroll")}
