"use server";
import { revalidatePath } from "next/cache";
import { prisma } from "../../../src/lib/prisma";
import { requireCurrentWorkspace } from "../../../src/auth/current-workspace";
import { monthlyStraightLine } from "../../../src/application/workforce/workforce-center-service";
const text=(fd:FormData,key:string)=>String(fd.get(key)??"").trim();
const money=(fd:FormData,key:string)=>{const raw=text(fd,key).replace(/[,\s]/g,"");if(!/^\d+$/.test(raw))throw new Error(`INVALID_${key.toUpperCase()}`);return BigInt(raw)};
export async function createFixedAssetAction(fd:FormData){const c=await requireCurrentWorkspace();if(c.role==="VIEWER")throw new Error("ASSET_WRITE_FORBIDDEN");const code=text(fd,"code"),name=text(fd,"name"),acquisitionCost=money(fd,"acquisitionCost"),residualValue=money(fd,"residualValue"),usefulLifeMonths=Number(text(fd,"usefulLifeMonths")),acquisitionDate=new Date(text(fd,"acquisitionDate"));monthlyStraightLine(acquisitionCost,residualValue,usefulLifeMonths);if(!code||!name||!Number.isFinite(acquisitionDate.getTime()))throw new Error("ASSET_REQUIRED_FIELDS");await prisma.fixedAsset.create({data:{workspaceId:c.workspace.id,code,name,acquisitionDate,acquisitionCost,residualValue,usefulLifeMonths}});revalidatePath("/app/fixed-assets")}
export async function postDepreciationAction(fd:FormData){const c=await requireCurrentWorkspace();if(c.role==="VIEWER")throw new Error("ASSET_WRITE_FORBIDDEN");const assetId=text(fd,"assetId"),periodDate=new Date(text(fd,"periodDate"));const asset=await prisma.fixedAsset.findFirst({where:{id:assetId,workspaceId:c.workspace.id,status:"ACTIVE"},include:{depreciationEntries:true}});if(!asset||!Number.isFinite(periodDate.getTime()))throw new Error("ASSET_NOT_FOUND");const monthly=monthlyStraightLine(asset.acquisitionCost,asset.residualValue,asset.usefulLifeMonths),accumulated=asset.depreciationEntries.reduce((s,r)=>s+r.amount,0n),remaining=asset.acquisitionCost-asset.residualValue-accumulated;if(remaining<=0n)throw new Error("ASSET_FULLY_DEPRECIATED");await prisma.assetDepreciation.create({data:{workspaceId:c.workspace.id,assetId,periodDate,amount:monthly>remaining?remaining:monthly,note:"استهلاک ماهانه خط مستقیم"}});revalidatePath("/app/fixed-assets")}
