import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata={title:"تماس و درخواست پایلوت",description:"درخواست پایلوت و دسترسی اولیه به تسویا برای تیم‌های مالی و کسب‌وکارها.",alternates:{canonical:"/contact"}};
const paths=[
["پایلوت کسب‌وکار","برای ارزیابی گردش‌کار تسویه و کنترل عملیات در یک سناریوی محدود."],
["همکاری محصول","برای کسب‌وکارها و تیم‌هایی که مسئله واقعی در تسویه، شواهد یا مغایرت‌گیری دارند."],
["یکپارچه‌سازی آینده","برای بررسی فنی API، داده و اتصال‌های معتبر پس از آماده‌شدن لایه Production."]
];
export default function ContactPage(){return <main className="min-h-screen bg-[#f4f7fb] px-4 py-14 text-[#0b1220] sm:px-6"><div className="mx-auto max-w-6xl"><section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[32px] bg-[#0f223d] p-7 text-white sm:p-10"><div className="text-xs font-black text-[#63dfd4]">ارتباط با تسویا</div><h1 className="mt-3 text-4xl font-black leading-[1.4]">از یک مسئله واقعی مالی شروع کنیم.</h1><p className="mt-5 max-w-xl text-sm leading-8 text-white/65">در دسترسی اولیه، هدف فروش یک وعده نیست؛ مسئله عملیاتی، گردش‌کار و معیار موفقیت پایلوت را مشخص می‌کنیم.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/demo" className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-[#0f223d]">مشاهده دمو</Link><Link href="/security" className="rounded-2xl border border-white/15 px-5 py-3 text-sm font-black">مدل امنیت</Link></div></div><aside className="rounded-[32px] border border-black/5 bg-white p-7 sm:p-8"><div className="text-sm font-black">فرآیند دسترسی اولیه</div><ol className="mt-5 space-y-4 text-sm leading-7 text-[#657184]"><li><b className="text-[#0b1220]">۱.</b> تعریف مسئله و حجم عملیات</li><li><b className="text-[#0b1220]">۲.</b> انتخاب دامنه محدود پایلوت</li><li><b className="text-[#0b1220]">۳.</b> ارزیابی نتیجه قبل از هر اتصال مالی واقعی</li></ol><p className="mt-6 rounded-2xl bg-[#f5f8fb] p-4 text-xs leading-6 text-[#687487]">کانال دریافت درخواست و CRM رسمی در مرحله عملیاتی بعدی متصل می‌شود؛ این صفحه فعلاً مسیر رسمی ارزیابی محصول است.</p></aside></section><section className="mt-5 grid gap-4 md:grid-cols-3">{paths.map(([a,b])=><article key={a} className="rounded-[26px] bg-white p-6"><h2 className="font-black">{a}</h2><p className="mt-3 text-sm leading-7 text-[#657184]">{b}</p></article>)}</section></div></main>}
