import {WorkspaceShell} from "../../../src/components/workspace/shell";
import {requireCurrentWorkspace} from "../../../src/auth/current-workspace";
import {listSales,listSalesOptions} from "../../../src/application/sales/sales-service";
import {SalesForm} from "./sales-form";
import {approveSaleAction,postSaleAction,submitSaleAction} from "./actions";
const money=(v:bigint)=>`${new Intl.NumberFormat("fa-IR").format(v)} ریال`;
const label:Record<string,string>={DRAFT:"پیش‌نویس",SUBMITTED:"ارسال‌شده",APPROVED:"تأییدشده",POSTED:"ثبت مالی",PAID:"وصول‌شده",CANCELLED:"لغو"};
export default async function SalesPage(){const c=await requireCurrentWorkspace();const[o,sales]=await Promise.all([listSalesOptions(c.workspace.id),listSales(c.workspace.id)]);const revenue=sales.filter(x=>x.status==="POSTED"||x.status==="PAID").reduce((a,x)=>a+x.total,0n);const cogs=sales.reduce((a,x)=>a+x.cogsTotal,0n);
return <WorkspaceShell eyebrow="فروش، موجودی و دریافتنی" title="فاکتورهای فروش">
<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["فروش ثبت‌شده",money(revenue)],["بهای تمام‌شده",money(cogs)],["سود ناخالص",money(revenue-cogs)],["اسناد",new Intl.NumberFormat("fa-IR").format(sales.length)]].map(([a,b])=><article key={a} className="rounded-2xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">{a}</div><div className="mt-3 text-xl font-black">{b}</div></article>)}</section>
<section className="mt-5"><h2 className="mb-3 text-xl font-black">فاکتور جدید</h2><SalesForm customers={o.customers} warehouses={o.warehouses} items={o.items}/></section>
<section className="mt-5 overflow-x-auto rounded-3xl border bg-white"><table className="w-full min-w-[900px] text-right text-xs"><thead className="bg-slate-50"><tr>{["شماره","مشتری","مبلغ","COGS","وضعیت","عملیات"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{sales.length===0?<tr><td colSpan={6} className="p-10 text-center">هنوز فروشی ثبت نشده است.</td></tr>:sales.map(s=><tr key={s.id} className="border-t"><td className="p-4 font-black">{s.invoiceNumber}</td><td className="p-4">{s.customer.name}</td><td className="p-4">{money(s.total)}</td><td className="p-4">{money(s.cogsTotal)}</td><td className="p-4">{label[s.status]}</td><td className="p-4">{s.status==="DRAFT"?<form action={async()=>{"use server";await submitSaleAction(s.id)}}><button className="rounded-lg border px-3 py-2">ارسال</button></form>:s.status==="SUBMITTED"?<form action={async()=>{"use server";await approveSaleAction(s.id)}}><button className="rounded-lg border px-3 py-2">تأیید</button></form>:s.status==="APPROVED"?<form action={async()=>{"use server";await postSaleAction(s.id)}}><button className="rounded-lg bg-[#102845] px-3 py-2 text-white">ثبت مالی</button></form>:<span>ثبت شده</span>}</td></tr>)}</tbody></table></section>
</WorkspaceShell>}
